### ISSUE TITLE
Wildshape on page without grid enabled makes the token disappear

### ISSUE THREAD

**Issue by SleepyBandit** [ocangelo/roll20#1]
Script works great on a grid enabled page! But I first tested it on a non-grid page and the token disappears when using the script. Looks like it has nothing to measure size to and so makes it essentially 0 width x height. 

May not be anything you can do about this, and not a huge issue since I plan to always use grid maps. But it is something to be aware of.

**Comment by ocangelo** [comment]
thanks, I will have a look!

**Comment by ocangelo** [comment]
i am not doing anything specific about measuring the size, it's always setting the token size to 70 x createureSize so it should work... unless sizes need to be set differently on pages that don't have the grid enabled.

i am going to have to see if i can find any info in the API docs about this.

**Comment by ocangelo** [comment]
found the issue and checked in a fix for it, thanks again for the bug report :)
