### ISSUE TITLE
ERROR: Cannot find wildshape resource = wild shape

### ISSUE THREAD

**Issue by krippee** [ocangelo/roll20#2]
After installing and importing the creatures from a folder I received the following error when trying to perform wild shape through the` !ws` command.

`(From WildShape): (GM) ERROR: Cannot find wildshape resource = wild shape`

**Comment by krippee** [comment]
Just tested on individual import, same issue persists

**Comment by bjarki10** [comment]
> After installing and importing the creatures from a folder I received the following error when trying to perform wild shape through the` !ws` command.
> 
> `(From WildShape): (GM) ERROR: Cannot find wildshape resource = wild shape`

It's because it can't find the wild shape resource on the character sheet if the character sheet dosen't have it rename a Class Resource to "wild shape"

**Comment by ocangelo** [comment]
I can fix the default tomorrow, but for now what you can do is clear up the "wild shape resource" setting in the main config (chat menu)

**Comment by ocangelo** [comment]
changed the default on the resource to be empty
