### ISSUE TITLE
Changing roll type and dynamic lighting

### ISSUE THREAD

**Issue by tsansom** [ocangelo/roll20#3]
First off, thanks for making this script - it has removed a lot of the hassle of dealing with a high level moon druid on roll20. 

I don't see any options to change the format of the rolls (toggle advantage, roll damage, etc). I had to modify the script to change those universally. 

Also, do you have any plans on updating this to use the new dynamic lighting features of roll20?

**Comment by ocangelo** [comment]
You should see those settings in the main config under PC Settings and NPC Settings.

For the new dynamic lighting i know that they have a lot of bugs, I am waiting until they finalize the tech to add support for it
